language: "node_js"
sudo: false

node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"

notifications:
  email:
    on_success: never
    on_failure: never

before_script:
  - npm install standard
  - standard

script:
  - npm install istanbul
  - istanbul cover test.js

after_success:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls
